name: Demo-CiCd

on: 
  push:
    branches:
      - main

jobs:
  build_apk:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Setup Java
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Setup Gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      # Grant execute permissions for gradlew (This is relevant only if required)
      - name: Grant execute permissions for gradlew
        run: chmod +x ./gradlew

      # Build the APK
      - name: Build APK
        run: ./gradlew assembleDebug

      # Upload the APK as an artifact
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: dsTemplate.apk
          path: app/build/outputs/apk/debug/app-debug.apk
